### ISSUE TITLE
Question: equivalent of working_hours #advance_to_working_time ?

### ISSUE THREAD

**Issue by jakcharlton** [zendesk/biz#102]
Like the look of this gem and it's API more than working_hours, but does it have an equivalent way to calculate the next working time or the end of the working day as the working_hours gem does?

**Comment by craiglittle** [comment]
Hey, @jakcharlton!

There aren't any top-level methods for these operations, but they can be derived (currently, one more easily than the other) using the gem.

For the next working time:
```ruby
Biz.time(0, :hours).after(Time.now)
```
or:
```ruby
Biz.periods.after(Time.now).first.start_time
```

For the end of the working day, it's a bit more of a mouthful at the moment:
```ruby
Biz
  .periods
  .after(Time.now)
  .timeline
  .until(
    Biz.in_zone.on_date(
      Biz.in_zone.local(Time.now).to_date, 
      Biz::DayTime.endnight
    )
  )
  .to_a
  .last
  .end_time
```

Having to do that exercise made me realized that there's a gap in the gem's features that can be easily filled.

I'll add a method to take care of all of the above logic so that you'd only need to do the following in the future:
```ruby
Biz.periods.today.last.end_time
```

I'll keep this issue open until that new method has been written.

**Comment by jakcharlton** [comment]
That's awesome, thanks for the reply, and the "hotfix" :)
