### ISSUE TITLE
NoMethodError: undefined method `on' for #<Biz::Periods::Proxy:0x007f9b164d5d10>

### ISSUE THREAD

**Issue by megetron** [zendesk/biz#107]
Thanks for this great gem.

```

      biz = Biz::Schedule.new do |config|
        config.hours = {
          mon: {'09:00' => '17:00'},
          tue: {'00:00' => '24:00'},
          wed: {'09:00' => '17:00'},
          thu: {'09:00' => '12:00', '13:00' => '17:00'},
          sat: {'10:00' => '14:00'}
        }
        config.holidays = [Date.new(2014, 1, 1), Date.new(2014, 12, 25)]
        config.time_zone = 'Asia/Jerusalem'
      end
     biz.periods.on(Date.today)

```

gives me:
NoMethodError: undefined method `on' for #<Biz::Periods::Proxy:0x007f9b164d5d10>

**Comment by craiglittle** [comment]
Whoops, that's because that feature was recently merged and hasn't been included in a release yet. I was hoping to take a crack at [this](https://github.com/zendesk/biz/issues/103) feature request before cutting a new release.

Give me until the end of the week and I'll ship a new version, one way or the other.

**Comment by megetron** [comment]
Thank you:)

**Comment by craiglittle** [comment]
I haven't had a chance to get to that other feature request yet, so I went ahead with cutting a new release.

Enjoy `v1.7.0`!
