### ISSUE TITLE
Rails - global configuration doesn't work

### ISSUE THREAD

**Issue by oslyak** [zendesk/biz#18]
I try to use it with Rails.
Created config/initializers/biz.rb

    Biz.configure do |config|
      config.hours = {
        mon: {'10:00' => '19:00'},
        tue: {'10:00' => '19:00'},
        wed: {'10:00' => '19:00'},
        thu: {'10:00' => '19:00'},
        sat: {'10:00' => '19:00'}
      }

      config.holidays =  [Date.new(2016, 1, 1), Date.new(2017, 1, 1)]

      config.time_zone = 'Europe/Kiev'

    end

    Biz::Schedule.new do |config|
      config.hours = {
        mon: {'10:00' => '19:00'},
        tue: {'10:00' => '19:00'},
        wed: {'10:00' => '19:00'},
        thu: {'10:00' => '19:00'},
        sat: {'10:00' => '19:00'}
      }

      config.holidays =  [Date.new(2016, 1, 1), Date.new(2017, 1, 1)]

      config.time_zone = 'Europe/Kiev'
    end

In config/application.rb added

    require 'biz'
    require 'biz/core_ext'

But when try to use Biz in view I got exception: ActionView::Template::Error (Biz has not been configured)

Works only  if configure Biz in Controller method.

How to configure it to use with Rails?

**Comment by craiglittle** [comment]
Hey, @oslyak!

When configuring the top-level schedule, `biz` creates [one schedule per thread](https://github.com/zendesk/biz/blob/ad710710eece00539aa1192b2131e59e4282f4c5/lib/biz.rb#L18).

Are you using a threaded server such as [`puma`](https://github.com/puma/puma)? If so, you *will* need to configure `biz` on a per-thread basis. If you want to continue with centralizing the configuration, check out [`on_worker_boot`](https://www.omniref.com/ruby/gems/puma/2.6.0/java/symbols/Puma::Configuration::DSL/on_worker_boot). Otherwise, it sounds like configuring it in the controller or a middleware is your best bet.

I'm working on a project called [`biz-rails`](https://github.com/craiglittle/biz-rails) to make it easier to work with `biz` in a Rails environment out of the box. You might want to keep an eye out for that.

**Comment by craiglittle** [comment]
@oslyak, I don't see anything actionable here on our part, so I'm going to close this for now. Please let me know if you continue to run into any issues with `biz` that you can't resolve.

**Comment by craiglittle** [comment]
@oslyak, one more suggestion: If you want global schedule shared across threads, you can always assign it to a global variable:
```ruby
$biz = Biz::Schedule.new do |config|
  # ...
end
```

**Comment by oslyak** [comment]
Thank You.


2015-03-27 21:35 GMT+02:00 Craig Little <notifications@github.com>:

> @oslyak <https://github.com/oslyak>, one more suggestion: If you want
> global schedule shared across threads, you can always assign it to a global
> variable:
>
> $biz = Biz::Schedule.new do |config|
>   # ...end
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zendesk/biz/issues/18#issuecomment-87067295>.
>



-- 
З найкращими побажаннями!
                   "СІРІУС центр автоматизації обліку"   www.sirius.if.ua
Осляк Антон. +38 050 562-87-78
м. Івано-Франківськ, вул. Новгородська 39а   тел/факс +38 (0342)75-40-44
