### ISSUE TITLE
invalid configuration causes app to explode

### ISSUE THREAD

**Issue by mfkp** [zendesk/biz#31]
Just ran into this in my production system.

If you pass in an empty hours hash in `config.hours`, or if a single day has an empty hash, and you do something like:

```ruby
biz = Biz::Schedule.new do |config|
  config.hours = {}
end
```
```ruby
biz.periods
  .after(local_date.beginning_of_day)
  .timeline
  .forward
  .until(local_date.end_of_day)
  .to_a
```

then it'll spin forever and blow up your server.

This happened to me because I have subtractive hours, so sometimes it turns out that there can be no hours for a certain timeframe.

**Comment by craiglittle** [comment]
Hey, @mfkp!

One solution for your particular use case is to return early if the configuration is empty, avoiding the calls to `biz` entirely.

From the prospective of `biz`, given that methods like `Biz::time` would provide nonsensical results when provided an empty configuration, I think the solution to this issue is to raise a configuration validation error upfront at configuration time.

Does that seem reasonable?

**Comment by mfkp** [comment]
Yeah, raising an error seems like a valid solution. Really, anything is better than melting the cpu :smile: 

Took me a while to track it down too, something loud like that would make it easier to find next time.
