### ISSUE TITLE
The ability to specify work days? :)

### ISSUE THREAD

**Issue by fredwu** [zendesk/biz#5]
Hi,

Just come across this gem and I was wondering whether it's on your roadmap to add support for specifying weekend days as working days.

Thanks! :)

**Comment by craiglittle** [comment]
Yep, that's supported!

Here's an example schedule with business hours during every day of the week, including weekend days:
```ruby
Biz::Schedule.new do |config|
  config.business_hours = {
    mon: {'09:00' => '17:00'},
    tue: {'09:00' => '17:00'},
    wed: {'09:00' => '17:00'},
    thu: {'09:00' => '17:00'},
    fri: {'09:00' => '17:00'},
    sat: {'10:00' => '14:00'},
    sun: {'10:00' => '14:00'}
  }
end
```

Does that make sense?

**Comment by fredwu** [comment]
Thanks for the prompt response! :)

Yep, that's what I thought how it could be done, although for my specific use case, I only like to specify specific dates as working days, e.g. Chinese New Year holiday essentially swaps two weekend days as working days. The code you provided would then require specifying all "normal" weekend days as holidays.

**Comment by craiglittle** [comment]
Ah, that's interesting. It sounds like you're looking for something like "reverse holidays" where the time is on instead of off. I don't know if that's a use case we'd support in the gem proper, but it's an interesting concept for a potential extension.

In any case, it could be approximated by configuring business hours for the weekend as necessary for the Chinese New Year and then configuring all other "normal" weekend dates as holidays.

It wouldn't be the most elegant solution in the world, but it would be accurate!

**Comment by fredwu** [comment]
> It sounds like you're looking for something like "reverse holidays" where the time is on instead of off.

Yep, exactly!

> I don't know if that's a use case we'd support in the gem proper, but it's an interesting concept for a potential extension.

No worries, when I have time I might look into it. :)

Thanks for such quick responses, I appreciate it!

**Comment by ziweizhou** [comment]
Is it possible to implement this feature? I need it as well for my app. 

Thanks a lot.

**Comment by craiglittle** [comment]
@fredwu @ziweizhou 

I wanted to let you know that I just merged a PR to implement this feature: https://github.com/zendesk/biz/pull/109

Check it out, and let me know what you think!
