### ISSUE TITLE
Period end time is not business hours

### ISSUE THREAD

**Issue by mwean** [zendesk/biz#62]
I just found that the `end_time` of a period is not considered a business hour.

```ruby
schedule = Biz::Schedule.new do |config|
  config.hours = {
    mon: { '07:00' => '18:00' },
    tue: { '07:00' => '18:00' },
    wed: { '07:00' => '18:00' },
    thu: { '07:00' => '18:00' },
    fri: { '07:00' => '18:00' }
  }
end

wednesday_night = Time.utc(2016, 4, 13, 20)
#=> 2016-04-13 20:00:00 UTC

end_of_business = schedule.periods.before(wednesday_night).first.end_time
#=> 2016-04-13 18:00:00 UTC

schedule.business_hours?(end_of_business)
#=> false
```

I didn't dig too deeply, but it looks like the issue is [here](https://github.com/zendesk/biz/blob/master/lib/biz/interval.rb#L37) `(start_time...end_time).cover?` where it's not including the `end_time` in the range. Before I made a PR to change this, I wanted to check if this exclusion was intentional. Thanks!

**Comment by craiglittle** [comment]
Yes, the exclusion is [definitely intentional](https://github.com/zendesk/biz/blob/54583393d90519671eea7f5b37b84a44f3f02fc5/spec/interval_spec.rb#L142-L148).

This is one of those things, like business day calculations, where the "right" answer is ambiguous and highly context-dependent as I can see arguments for both sides depending on your use case.

I'm inclined to leave it more strict (i.e. excluding the `end_time`) as the default behavior. On the bright side, this is another one of those aspects that you can wrap if you'd like.

Here's one way:

```ruby
def in_hours?(schedule, time)
  schedule.periods.before(time).first.end_time == time
end
```

**Comment by mwean** [comment]
Ok, sounds good. Thanks!
