### ISSUE TITLE
TimeSegment generation is really slow for schedules with lots of holidays

### ISSUE THREAD

**Issue by pocman** [zendesk/biz#63]
Hi,
The TimeSegment generation is really slow ~0.3s for a 7.day simple generation with lots of holidays.
Building a schedule with filtered holidays seems to fix that.
```
schedule
        .periods.after(calendar_start)
        .timeline.until(calendar_end).to_a
```

**Comment by craiglittle** [comment]
Thanks for the report. I've kinda known this was a thing, but hadn't gotten around to addressing it.

I'm away on vacation at the moment, but I'll get a fix out next week once I'm back.

**Comment by craiglittle** [comment]
After digging into this further, there simply isn't a great way to address this as the periods generator doesn't know at the time it's constructed which holidays will be relevant. My recommendation is that if you 1) use the holidays feature, 2) know there's the possibility you'll have a lot of holidays, and 3) performance is a big concern, like you suggested, pre-filter the holidays for the calculations you're about to run to improve performance.

With that said, I've created [a PR](https://github.com/zendesk/biz/pull/65) to add this recommendation to the `README` so other users can benefit if they encounter this issue.

Thanks again for the report. I'll keep it in mind in the chance a more satisfactory way to address the issue comes to me.

**Comment by pocman** [comment]
Thanks, I also suspected that the current structure was an issue.
I couldn't find a nice way to clone a `Biz::Schedule` while filtering the internal `config.holidays`.
Could you give it a try ?

Thanks a lot for your feedback and reactivity :D

**Comment by craiglittle** [comment]
If you've already created a schedule, you could pull the holidays out (using something like `schedule.holidays.map(&:to_date)`), filter, and create another schedule, right?
