### ISSUE TITLE
Business day calculation on weekend ignores time

### ISSUE THREAD

**Issue by zdicesare** [zendesk/biz#80]
```
2.3.1 :028 > biz = Biz::Schedule.new do |config|
2.3.1 :029 >     config.time_zone = "America/New_York"
2.3.1 :030?>   end
 => #<Biz::Schedule:0x007fa5cd591eb8 @configuration=#<Biz::Configuration:0x007fa5cd591e40 @raw=#<struct Biz::Configuration::Raw hours={:mon=>{"09:00"=>"17:00"}, :tue=>{"09:00"=>"17:00"}, :wed=>{"09:00"=>"17:00"}, :thu=>{"09:00"=>"17:00"}, :fri=>{"09:00"=>"17:00"}}, breaks=[], holidays=[], time_zone="America/New_York">>> 

2.3.1 :031 > time = Time.parse("Sat, 06 Aug 2016 13:30:01 EDT -04:00")
 => 2016-08-06 13:30:01 -0400 

2.3.1 :032 > biz.time(1, :seconds).after(time)
 => 2016-08-08 13:00:01 UTC 

2.3.1 :033 > biz.time(1, :seconds).after(time).in_time_zone("America/New_York")
 => Mon, 08 Aug 2016 09:00:01 EDT -04:00 

2.3.1 :034 > biz.time(1, :hour).after(time).in_time_zone("America/New_York")
 => Mon, 08 Aug 2016 10:00:00 EDT -04:00 

2.3.1 :035 > biz.time(1, :day).after(time).in_time_zone("America/New_York")
 => Mon, 08 Aug 2016 13:30:01 EDT -04:00 
```

This final example here is unintuitive to me. Unlike `seconds` and `hours`, `day` is ignoring the time aspect of the datetime. I would expect the result to be end of day Monday / beginning of day Tuesday. 

In short, asking for `days after` on any time during a weekend will ignore the time component. So the answer it gives isn't really a full business day after- it's only half a business day after.

However, I see this same behavior in other business day gems as well (`working_hours`, and `business_time`), so I'm not sure if this is a bug or just thinking about weekend originating business day calculations in the wrong way. 

One workaround we've discussed is to use `seconds` calculations instead of `day` calculations. Alternatively, we could manually fast forward if we occur on a weekend to the beginning of the next working day.

Any thoughts- is this a bug or should I be thinking about business days differently?

**Comment by craiglittle** [comment]
Hey there!

This is the expected behavior. There's a [blurb](https://github.com/zendesk/biz#day-calculation-semantics) in the `README` that discusses the reasoning and logic that's followed.

You can find more discussion in https://github.com/zendesk/biz/issues/56 and https://github.com/zendesk/biz/issues/73.

In short, use cases can vary with an ambiguous concept like a "day", particularly when weekdays with multiple intervals come into play.

Depending on your typical schedule, there are ways to easily wrap `biz` to get your desired behavior. Check out the first linked issue above for one approach.

Let me know if you have problems figuring out the implementation that works for you; I'm happy to help.

**Comment by zdicesare** [comment]
Thank you for confirmation @craiglittle !
